[features]
seeds = false
[programs.localnet]
vesting = "E2945Kfx1HKGiK3QFzLZSBn3hxscJx9vpjPYkm8qffDS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/justinlee/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
